-- Bootstrap books schema for remote environment with broken migration history
-- Generated by composing existing idempotent migrations in deterministic order.

-- organizations.features/menu_labels/menu_order에 books 메뉴를 추가
-- 목표:
-- 1) 통합 플랫폼 내 도서 UI를 별도 제품처럼 운영
-- 2) 기관별로 books 기능을 ON/OFF 가능

alter table public.organizations
  alter column features set default '{
    "equipment": true,
    "spaces": true,
    "vehicles": false,
    "books": false
  }'::jsonb;

alter table public.organizations
  alter column menu_labels set default '{
    "equipment": "물품",
    "spaces": "공간",
    "vehicles": "차량",
    "books": "도서"
  }'::jsonb;

alter table public.organizations
  alter column menu_order set default '[
    {"key": "equipment", "enabled": true},
    {"key": "spaces", "enabled": true},
    {"key": "vehicles", "enabled": false},
    {"key": "books", "enabled": false}
  ]'::jsonb;

update public.organizations
set features = coalesce(features, '{}'::jsonb) || jsonb_build_object(
  'books',
  coalesce((features->>'books')::boolean, false)
)
where features is null or not (features ? 'books');

update public.organizations
set menu_labels = coalesce(menu_labels, '{}'::jsonb) || jsonb_build_object(
  'books',
  coalesce(menu_labels->>'books', '도서')
)
where menu_labels is null or not (menu_labels ? 'books');

update public.organizations
set menu_order = jsonb_build_array(
  jsonb_build_object(
    'key', 'equipment',
    'enabled', coalesce((features->>'equipment')::boolean, true)
  ),
  jsonb_build_object(
    'key', 'spaces',
    'enabled', coalesce((features->>'spaces')::boolean, true)
  ),
  jsonb_build_object(
    'key', 'vehicles',
    'enabled', coalesce((features->>'vehicles')::boolean, false)
  ),
  jsonb_build_object(
    'key', 'books',
    'enabled', coalesce((features->>'books')::boolean, false)
  )
)
where menu_order is null or menu_order = '[]'::jsonb;

update public.organizations
set menu_order = coalesce(menu_order, '[]'::jsonb) || jsonb_build_array(
  jsonb_build_object(
    'key', 'books',
    'enabled', coalesce((features->>'books')::boolean, false)
  )
)
where not exists (
  select 1
  from jsonb_array_elements(coalesce(menu_order, '[]'::jsonb)) as item
  where item->>'key' = 'books'
);

-- 도서 대여 관리 MVP 스키마
-- 목적:
-- 1) 기관/개인 도서 등록
-- 2) 대여 신청/승인/반납
-- 3) 2차 확장(교환/선물/기증)용 기본 테이블

-- 0) 테이블 생성
create table if not exists public.book_items (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  owner_scope text not null default 'organization', -- organization | member
  owner_profile_id uuid references public.profiles(id) on delete set null,
  title text not null,
  author text,
  publisher text,
  published_year integer,
  isbn text,
  cover_image_url text,
  category text,
  tags text[] default '{}',
  description text,
  condition text default 'good', -- new | good | fair | poor
  share_mode text not null default 'lend_only', -- lend_only | exchange_allowed | gift_allowed | donation_only
  status text not null default 'available', -- available | requested | borrowed | overdue | archived
  is_active boolean default true not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint book_items_owner_scope_chk check (owner_scope in ('organization', 'member')),
  constraint book_items_condition_chk check (condition in ('new', 'good', 'fair', 'poor')),
  constraint book_items_share_mode_chk check (share_mode in ('lend_only', 'exchange_allowed', 'gift_allowed', 'donation_only')),
  constraint book_items_status_chk check (status in ('available', 'requested', 'borrowed', 'overdue', 'archived')),
  constraint book_items_owner_profile_chk check (
    (owner_scope = 'organization' and owner_profile_id is null)
    or (owner_scope = 'member' and owner_profile_id is not null)
  ),
  constraint book_items_published_year_chk check (
    published_year is null or (published_year between 1000 and 2100)
  )
);

create table if not exists public.book_loans (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  book_item_id uuid references public.book_items(id) on delete cascade not null,
  borrower_id uuid references public.profiles(id) on delete cascade not null,
  owner_profile_id uuid references public.profiles(id) on delete set null,
  status text not null default 'requested', -- requested | approved | borrowed | returned | rejected | cancelled | overdue
  requested_at timestamp with time zone default timezone('utc'::text, now()) not null,
  approved_at timestamp with time zone,
  borrowed_at timestamp with time zone,
  due_at timestamp with time zone,
  returned_at timestamp with time zone,
  note text,
  return_note text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint book_loans_status_chk check (status in ('requested', 'approved', 'borrowed', 'returned', 'rejected', 'cancelled', 'overdue')),
  constraint book_loans_due_after_requested_chk check (
    due_at is null or due_at > requested_at
  )
);

-- 2차 확장용: 교환/선물/기증 게시물
create table if not exists public.book_transfer_offers (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  book_item_id uuid references public.book_items(id) on delete cascade not null,
  owner_profile_id uuid references public.profiles(id) on delete cascade not null,
  offer_type text not null, -- exchange | gift | donation
  status text not null default 'open', -- open | matched | completed | cancelled
  wanted_text text,
  note text,
  matched_profile_id uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  completed_at timestamp with time zone,
  constraint book_transfer_offers_type_chk check (offer_type in ('exchange', 'gift', 'donation')),
  constraint book_transfer_offers_status_chk check (status in ('open', 'matched', 'completed', 'cancelled'))
);

-- 1) 인덱스
create index if not exists idx_book_items_org on public.book_items(organization_id);
create index if not exists idx_book_items_owner_profile on public.book_items(owner_profile_id);
create index if not exists idx_book_items_status on public.book_items(status);
create index if not exists idx_book_items_title on public.book_items(title);
create index if not exists idx_book_items_created_at on public.book_items(created_at desc);

create index if not exists idx_book_loans_org on public.book_loans(organization_id);
create index if not exists idx_book_loans_book_item on public.book_loans(book_item_id);
create index if not exists idx_book_loans_borrower on public.book_loans(borrower_id);
create index if not exists idx_book_loans_status on public.book_loans(status);
create index if not exists idx_book_loans_due_at on public.book_loans(due_at);

create index if not exists idx_book_transfer_offers_org on public.book_transfer_offers(organization_id);
create index if not exists idx_book_transfer_offers_owner on public.book_transfer_offers(owner_profile_id);
create index if not exists idx_book_transfer_offers_status on public.book_transfer_offers(status);
create index if not exists idx_book_transfer_offers_type on public.book_transfer_offers(offer_type);

-- 2) updated_at 트리거 함수
create or replace function public.set_book_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_book_items_set_updated_at on public.book_items;
create trigger trg_book_items_set_updated_at
before update on public.book_items
for each row execute function public.set_book_updated_at();

drop trigger if exists trg_book_loans_set_updated_at on public.book_loans;
create trigger trg_book_loans_set_updated_at
before update on public.book_loans
for each row execute function public.set_book_updated_at();

drop trigger if exists trg_book_transfer_offers_set_updated_at on public.book_transfer_offers;
create trigger trg_book_transfer_offers_set_updated_at
before update on public.book_transfer_offers
for each row execute function public.set_book_updated_at();

-- 3) RLS 활성화
alter table public.book_items enable row level security;
alter table public.book_loans enable row level security;
alter table public.book_transfer_offers enable row level security;

-- 4) 기존 정책 제거
drop policy if exists "book_items_select_same_org" on public.book_items;
drop policy if exists "book_items_insert_same_org" on public.book_items;
drop policy if exists "book_items_update_owner_or_manager" on public.book_items;
drop policy if exists "book_items_delete_owner_or_manager" on public.book_items;

drop policy if exists "book_loans_select_same_org" on public.book_loans;
drop policy if exists "book_loans_insert_borrower" on public.book_loans;
drop policy if exists "book_loans_update_borrower_or_owner_or_manager" on public.book_loans;

drop policy if exists "book_transfer_offers_select_same_org" on public.book_transfer_offers;
drop policy if exists "book_transfer_offers_insert_owner" on public.book_transfer_offers;
drop policy if exists "book_transfer_offers_update_owner_or_manager" on public.book_transfer_offers;

-- 5) book_items 정책
create policy "book_items_select_same_org"
on public.book_items
for select
to authenticated
using (
  organization_id = (
    select organization_id
    from public.profiles
    where id = auth.uid()
  )
);

create policy "book_items_insert_same_org"
on public.book_items
for insert
to authenticated
with check (
  organization_id = (
    select organization_id
    from public.profiles
    where id = auth.uid()
  )
  and created_by = auth.uid()
  and (
    (owner_scope = 'organization' and owner_profile_id is null)
    or (owner_scope = 'member' and owner_profile_id = auth.uid())
  )
);

create policy "book_items_update_owner_or_manager"
on public.book_items
for update
to authenticated
using (
  organization_id = (
    select organization_id
    from public.profiles
    where id = auth.uid()
  )
  and (
    owner_profile_id = auth.uid()
    or exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
      and p.role in ('admin', 'manager')
    )
  )
)
with check (
  organization_id = (
    select organization_id
    from public.profiles
    where id = auth.uid()
  )
);

create policy "book_items_delete_owner_or_manager"
on public.book_items
for delete
to authenticated
using (
  organization_id = (
    select organization_id
    from public.profiles
    where id = auth.uid()
  )
  and (
    owner_profile_id = auth.uid()
    or exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
      and p.role in ('admin', 'manager')
    )
  )
);

-- 6) book_loans 정책
create policy "book_loans_select_same_org"
on public.book_loans
for select
to authenticated
using (
  organization_id = (
    select organization_id
    from public.profiles
    where id = auth.uid()
  )
);

create policy "book_loans_insert_borrower"
on public.book_loans
for insert
to authenticated
with check (
  borrower_id = auth.uid()
  and organization_id = (
    select organization_id
    from public.profiles
    where id = auth.uid()
  )
  and exists (
    select 1
    from public.book_items bi
    where bi.id = book_item_id
      and bi.organization_id = (
        select organization_id
        from public.profiles
        where id = auth.uid()
      )
      and bi.is_active = true
      and bi.status in ('available', 'requested')
  )
);

create policy "book_loans_update_borrower_or_owner_or_manager"
on public.book_loans
for update
to authenticated
using (
  organization_id = (
    select organization_id
    from public.profiles
    where id = auth.uid()
  )
  and (
    borrower_id = auth.uid()
    or owner_profile_id = auth.uid()
    or exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
      and p.role in ('admin', 'manager')
    )
  )
)
with check (
  organization_id = (
    select organization_id
    from public.profiles
    where id = auth.uid()
  )
);

-- 7) book_transfer_offers 정책 (2차 기능 대비)
create policy "book_transfer_offers_select_same_org"
on public.book_transfer_offers
for select
to authenticated
using (
  organization_id = (
    select organization_id
    from public.profiles
    where id = auth.uid()
  )
);

create policy "book_transfer_offers_insert_owner"
on public.book_transfer_offers
for insert
to authenticated
with check (
  owner_profile_id = auth.uid()
  and organization_id = (
    select organization_id
    from public.profiles
    where id = auth.uid()
  )
);

create policy "book_transfer_offers_update_owner_or_manager"
on public.book_transfer_offers
for update
to authenticated
using (
  organization_id = (
    select organization_id
    from public.profiles
    where id = auth.uid()
  )
  and (
    owner_profile_id = auth.uid()
    or exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
      and p.role in ('admin', 'manager')
    )
  )
)
with check (
  organization_id = (
    select organization_id
    from public.profiles
    where id = auth.uid()
  )
);

-- 도서 대여 확장 스키마
-- 범위:
-- 1) 자율 대출/반납(스캔 + 서가코드 + 반납사진)
-- 2) 메모/서평
-- 3) AI 퀴즈
-- 4) 포인트/시상

-- 0) 기존 테이블 확장
alter table public.book_items
  add column if not exists copy_code text,
  add column if not exists shelf_code text,
  add column if not exists shelf_label text,
  add column if not exists self_checkout_enabled boolean not null default true;

create unique index if not exists idx_book_items_org_copy_code_unique
on public.book_items(organization_id, copy_code)
where copy_code is not null;

create index if not exists idx_book_items_org_shelf_code
on public.book_items(organization_id, shelf_code);

alter table public.book_loans
  add column if not exists checkout_method text not null default 'staff',
  add column if not exists checkout_scan_code text,
  add column if not exists checkout_scanned_at timestamp with time zone,
  add column if not exists return_method text,
  add column if not exists return_shelf_code text,
  add column if not exists return_photo_url text,
  add column if not exists return_verification_status text not null default 'not_required',
  add column if not exists return_verification_note text,
  add column if not exists return_verified_by uuid references public.profiles(id) on delete set null,
  add column if not exists return_verified_at timestamp with time zone;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'book_loans_checkout_method_chk'
      and conrelid = 'public.book_loans'::regclass
  ) then
    alter table public.book_loans
      add constraint book_loans_checkout_method_chk
      check (checkout_method in ('staff', 'self_scan'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'book_loans_return_method_chk'
      and conrelid = 'public.book_loans'::regclass
  ) then
    alter table public.book_loans
      add constraint book_loans_return_method_chk
      check (return_method is null or return_method in ('staff', 'self_photo'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'book_loans_return_verify_status_chk'
      and conrelid = 'public.book_loans'::regclass
  ) then
    alter table public.book_loans
      add constraint book_loans_return_verify_status_chk
      check (return_verification_status in ('not_required', 'pending', 'verified', 'rejected'));
  end if;
end $$;

create index if not exists idx_book_loans_org_checkout_method
on public.book_loans(organization_id, checkout_method);

create index if not exists idx_book_loans_org_return_verify_status
on public.book_loans(organization_id, return_verification_status);

-- 1) 자율 반납 증빙
create table if not exists public.book_return_evidences (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  loan_id uuid references public.book_loans(id) on delete cascade not null,
  book_item_id uuid references public.book_items(id) on delete cascade not null,
  returned_by uuid references public.profiles(id) on delete set null,
  shelf_code text,
  shelf_label text,
  photo_url text,
  photo_urls text[] default '{}',
  verify_status text not null default 'pending', -- pending | verified | rejected
  verify_note text,
  verified_by uuid references public.profiles(id) on delete set null,
  verified_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint book_return_evidences_status_chk check (verify_status in ('pending', 'verified', 'rejected'))
);

create index if not exists idx_book_return_evidences_org
on public.book_return_evidences(organization_id);

create index if not exists idx_book_return_evidences_loan
on public.book_return_evidences(loan_id);

create index if not exists idx_book_return_evidences_status
on public.book_return_evidences(verify_status);

drop trigger if exists trg_book_return_evidences_set_updated_at on public.book_return_evidences;
create trigger trg_book_return_evidences_set_updated_at
before update on public.book_return_evidences
for each row execute function public.set_book_updated_at();

-- 2) 메모/서평/독후감
create table if not exists public.book_notes (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  book_item_id uuid references public.book_items(id) on delete cascade not null,
  loan_id uuid references public.book_loans(id) on delete set null,
  author_id uuid references public.profiles(id) on delete set null,
  note_type text not null default 'memo', -- memo | review | reflection
  visibility text not null default 'organization', -- private | organization
  rating smallint,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  deleted_at timestamp with time zone,
  constraint book_notes_type_chk check (note_type in ('memo', 'review', 'reflection')),
  constraint book_notes_visibility_chk check (visibility in ('private', 'organization')),
  constraint book_notes_rating_chk check (rating is null or rating between 1 and 5)
);

create index if not exists idx_book_notes_org
on public.book_notes(organization_id);

create index if not exists idx_book_notes_book_item
on public.book_notes(book_item_id);

create index if not exists idx_book_notes_author
on public.book_notes(author_id);

create index if not exists idx_book_notes_created_at
on public.book_notes(created_at desc);

drop trigger if exists trg_book_notes_set_updated_at on public.book_notes;
create trigger trg_book_notes_set_updated_at
before update on public.book_notes
for each row execute function public.set_book_updated_at();

-- 3) AI 퀴즈
create table if not exists public.book_quiz_sessions (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  book_item_id uuid references public.book_items(id) on delete cascade not null,
  loan_id uuid references public.book_loans(id) on delete set null,
  participant_id uuid references public.profiles(id) on delete set null,
  level text not null default 'beginner', -- beginner | intermediate | advanced
  source_type text not null default 'hybrid', -- book_meta | user_note | hybrid
  status text not null default 'generated', -- generated | in_progress | completed | cancelled
  question_count integer not null default 0,
  correct_count integer not null default 0,
  score integer not null default 0,
  model_name text,
  prompt_version text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint book_quiz_sessions_level_chk check (level in ('beginner', 'intermediate', 'advanced')),
  constraint book_quiz_sessions_source_chk check (source_type in ('book_meta', 'user_note', 'hybrid')),
  constraint book_quiz_sessions_status_chk check (status in ('generated', 'in_progress', 'completed', 'cancelled'))
);

create index if not exists idx_book_quiz_sessions_org
on public.book_quiz_sessions(organization_id);

create index if not exists idx_book_quiz_sessions_participant
on public.book_quiz_sessions(participant_id);

create index if not exists idx_book_quiz_sessions_book_item
on public.book_quiz_sessions(book_item_id);

create index if not exists idx_book_quiz_sessions_status
on public.book_quiz_sessions(status);

drop trigger if exists trg_book_quiz_sessions_set_updated_at on public.book_quiz_sessions;
create trigger trg_book_quiz_sessions_set_updated_at
before update on public.book_quiz_sessions
for each row execute function public.set_book_updated_at();

create table if not exists public.book_quiz_questions (
  id uuid default gen_random_uuid() primary key,
  session_id uuid references public.book_quiz_sessions(id) on delete cascade not null,
  sequence integer not null,
  question_type text not null default 'mcq', -- mcq | short_answer | true_false
  prompt text not null,
  choices jsonb not null default '[]'::jsonb,
  answer_key text,
  explanation text,
  difficulty smallint,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint book_quiz_questions_type_chk check (question_type in ('mcq', 'short_answer', 'true_false')),
  constraint book_quiz_questions_difficulty_chk check (difficulty is null or difficulty between 1 and 5),
  constraint book_quiz_questions_sequence_unique unique (session_id, sequence)
);

create index if not exists idx_book_quiz_questions_session
on public.book_quiz_questions(session_id);

create table if not exists public.book_quiz_attempts (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  session_id uuid references public.book_quiz_sessions(id) on delete cascade not null,
  question_id uuid references public.book_quiz_questions(id) on delete cascade not null,
  participant_id uuid references public.profiles(id) on delete set null,
  answer_text text,
  is_correct boolean,
  score_delta integer not null default 0,
  answered_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create unique index if not exists idx_book_quiz_attempts_once_per_question
on public.book_quiz_attempts(session_id, question_id, participant_id);

create index if not exists idx_book_quiz_attempts_org_participant
on public.book_quiz_attempts(organization_id, participant_id);

-- 4) 포인트/시상
create table if not exists public.book_point_ledger (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  profile_id uuid references public.profiles(id) on delete cascade not null,
  source_type text not null, -- loan | return | note | quiz | bonus | penalty
  source_id uuid,
  points integer not null,
  note text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint book_point_ledger_source_type_chk check (source_type in ('loan', 'return', 'note', 'quiz', 'bonus', 'penalty'))
);

create index if not exists idx_book_point_ledger_org_profile
on public.book_point_ledger(organization_id, profile_id);

create index if not exists idx_book_point_ledger_created_at
on public.book_point_ledger(created_at desc);

create table if not exists public.book_reward_events (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  period_type text not null, -- monthly | quarterly | yearly
  period_key text not null,  -- ex) 2026-02, 2026-Q1, 2026
  status text not null default 'pending', -- pending | calculated | announced | closed
  starts_at timestamp with time zone not null,
  ends_at timestamp with time zone not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint book_reward_events_period_type_chk check (period_type in ('monthly', 'quarterly', 'yearly')),
  constraint book_reward_events_status_chk check (status in ('pending', 'calculated', 'announced', 'closed')),
  constraint book_reward_events_period_unique unique (organization_id, period_type, period_key)
);

create index if not exists idx_book_reward_events_org_status
on public.book_reward_events(organization_id, status);

drop trigger if exists trg_book_reward_events_set_updated_at on public.book_reward_events;
create trigger trg_book_reward_events_set_updated_at
before update on public.book_reward_events
for each row execute function public.set_book_updated_at();

create table if not exists public.book_reward_rankings (
  id uuid default gen_random_uuid() primary key,
  reward_event_id uuid references public.book_reward_events(id) on delete cascade not null,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  profile_id uuid references public.profiles(id) on delete cascade not null,
  total_points integer not null default 0,
  quiz_points integer not null default 0,
  note_points integer not null default 0,
  activity_points integer not null default 0,
  rank_no integer,
  prize_label text,
  awarded_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint book_reward_rankings_unique unique (reward_event_id, profile_id)
);

create index if not exists idx_book_reward_rankings_event
on public.book_reward_rankings(reward_event_id);

create index if not exists idx_book_reward_rankings_org_profile
on public.book_reward_rankings(organization_id, profile_id);

-- 5) 스캔 이벤트 로그
create table if not exists public.book_scan_events (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  actor_id uuid references public.profiles(id) on delete set null,
  loan_id uuid references public.book_loans(id) on delete set null,
  book_item_id uuid references public.book_items(id) on delete set null,
  event_type text not null, -- checkout_scan | return_scan | shelf_scan
  scanned_code text not null,
  result text not null, -- success | failed
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint book_scan_events_type_chk check (event_type in ('checkout_scan', 'return_scan', 'shelf_scan')),
  constraint book_scan_events_result_chk check (result in ('success', 'failed'))
);

create index if not exists idx_book_scan_events_org_created_at
on public.book_scan_events(organization_id, created_at desc);

create index if not exists idx_book_scan_events_actor
on public.book_scan_events(actor_id);

-- 6) RLS 활성화
alter table public.book_return_evidences enable row level security;
alter table public.book_notes enable row level security;
alter table public.book_quiz_sessions enable row level security;
alter table public.book_quiz_questions enable row level security;
alter table public.book_quiz_attempts enable row level security;
alter table public.book_point_ledger enable row level security;
alter table public.book_reward_events enable row level security;
alter table public.book_reward_rankings enable row level security;
alter table public.book_scan_events enable row level security;

-- 7) 정책 초기화
drop policy if exists "book_return_evidences_select_same_org" on public.book_return_evidences;
drop policy if exists "book_return_evidences_insert_self" on public.book_return_evidences;
drop policy if exists "book_return_evidences_update_manager" on public.book_return_evidences;

drop policy if exists "book_notes_select_same_org_or_private_owner" on public.book_notes;
drop policy if exists "book_notes_insert_author" on public.book_notes;
drop policy if exists "book_notes_update_author_or_manager" on public.book_notes;
drop policy if exists "book_notes_delete_author_or_manager" on public.book_notes;

drop policy if exists "book_quiz_sessions_select_same_org" on public.book_quiz_sessions;
drop policy if exists "book_quiz_sessions_insert_participant_or_manager" on public.book_quiz_sessions;
drop policy if exists "book_quiz_sessions_update_participant_or_manager" on public.book_quiz_sessions;

drop policy if exists "book_quiz_questions_select_same_org" on public.book_quiz_questions;
drop policy if exists "book_quiz_questions_insert_owner_or_manager" on public.book_quiz_questions;
drop policy if exists "book_quiz_questions_update_manager" on public.book_quiz_questions;

drop policy if exists "book_quiz_attempts_select_same_org" on public.book_quiz_attempts;
drop policy if exists "book_quiz_attempts_insert_participant" on public.book_quiz_attempts;

drop policy if exists "book_point_ledger_select_same_org" on public.book_point_ledger;
drop policy if exists "book_point_ledger_insert_manager" on public.book_point_ledger;

drop policy if exists "book_reward_events_select_same_org" on public.book_reward_events;
drop policy if exists "book_reward_events_insert_manager" on public.book_reward_events;
drop policy if exists "book_reward_events_update_manager" on public.book_reward_events;

drop policy if exists "book_reward_rankings_select_same_org" on public.book_reward_rankings;
drop policy if exists "book_reward_rankings_insert_manager" on public.book_reward_rankings;
drop policy if exists "book_reward_rankings_update_manager" on public.book_reward_rankings;

drop policy if exists "book_scan_events_select_same_org" on public.book_scan_events;
drop policy if exists "book_scan_events_insert_self" on public.book_scan_events;

-- 8) 공통 셀렉트 정책
create policy "book_return_evidences_select_same_org"
on public.book_return_evidences
for select
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_notes_select_same_org_or_private_owner"
on public.book_notes
for select
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and (visibility = 'organization' or author_id = auth.uid())
);

create policy "book_quiz_sessions_select_same_org"
on public.book_quiz_sessions
for select
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_quiz_questions_select_same_org"
on public.book_quiz_questions
for select
to authenticated
using (
  exists (
    select 1
    from public.book_quiz_sessions s
    where s.id = session_id
      and s.organization_id = (select organization_id from public.profiles where id = auth.uid())
  )
);

create policy "book_quiz_attempts_select_same_org"
on public.book_quiz_attempts
for select
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_point_ledger_select_same_org"
on public.book_point_ledger
for select
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_reward_events_select_same_org"
on public.book_reward_events
for select
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_reward_rankings_select_same_org"
on public.book_reward_rankings
for select
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_scan_events_select_same_org"
on public.book_scan_events
for select
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

-- 9) 입력/수정 정책
create policy "book_return_evidences_insert_self"
on public.book_return_evidences
for insert
to authenticated
with check (
  returned_by = auth.uid()
  and organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_return_evidences_update_manager"
on public.book_return_evidences
for update
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager')
  )
)
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_notes_insert_author"
on public.book_notes
for insert
to authenticated
with check (
  author_id = auth.uid()
  and organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_notes_update_author_or_manager"
on public.book_notes
for update
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and (
    author_id = auth.uid()
    or exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role in ('admin', 'manager')
    )
  )
)
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_notes_delete_author_or_manager"
on public.book_notes
for delete
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and (
    author_id = auth.uid()
    or exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role in ('admin', 'manager')
    )
  )
);

create policy "book_quiz_sessions_insert_participant_or_manager"
on public.book_quiz_sessions
for insert
to authenticated
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and (
    participant_id = auth.uid()
    or exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role in ('admin', 'manager')
    )
  )
);

create policy "book_quiz_sessions_update_participant_or_manager"
on public.book_quiz_sessions
for update
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and (
    participant_id = auth.uid()
    or exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role in ('admin', 'manager')
    )
  )
)
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_quiz_questions_insert_owner_or_manager"
on public.book_quiz_questions
for insert
to authenticated
with check (
  exists (
    select 1
    from public.book_quiz_sessions s
    where s.id = session_id
      and s.organization_id = (select organization_id from public.profiles where id = auth.uid())
      and (
        s.participant_id = auth.uid()
        or exists (
          select 1
          from public.profiles p
          where p.id = auth.uid()
            and p.role in ('admin', 'manager')
        )
      )
  )
);

create policy "book_quiz_questions_update_manager"
on public.book_quiz_questions
for update
to authenticated
using (
  exists (
    select 1
    from public.book_quiz_sessions s
    where s.id = session_id
      and s.organization_id = (select organization_id from public.profiles where id = auth.uid())
      and exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.role in ('admin', 'manager')
      )
  )
)
with check (
  exists (
    select 1
    from public.book_quiz_sessions s
    where s.id = session_id
      and s.organization_id = (select organization_id from public.profiles where id = auth.uid())
  )
);

create policy "book_quiz_attempts_insert_participant"
on public.book_quiz_attempts
for insert
to authenticated
with check (
  participant_id = auth.uid()
  and organization_id = (select organization_id from public.profiles where id = auth.uid())
  and exists (
    select 1
    from public.book_quiz_sessions s
    where s.id = session_id
      and s.participant_id = auth.uid()
      and s.organization_id = (select organization_id from public.profiles where id = auth.uid())
  )
);

create policy "book_point_ledger_insert_manager"
on public.book_point_ledger
for insert
to authenticated
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager')
  )
);

create policy "book_reward_events_insert_manager"
on public.book_reward_events
for insert
to authenticated
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and created_by = auth.uid()
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager')
  )
);

create policy "book_reward_events_update_manager"
on public.book_reward_events
for update
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager')
  )
)
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_reward_rankings_insert_manager"
on public.book_reward_rankings
for insert
to authenticated
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager')
  )
);

create policy "book_reward_rankings_update_manager"
on public.book_reward_rankings
for update
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager')
  )
)
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_scan_events_insert_self"
on public.book_scan_events
for insert
to authenticated
with check (
  actor_id = auth.uid()
  and organization_id = (select organization_id from public.profiles where id = auth.uid())
);

-- 도서 게임화 확장 (듀오링고식 경쟁/응원 + 선택형 시상)
-- 전제:
-- - 20260219_create_book_lending_mvp.sql
-- - 20260219_extend_book_lending_self_service.sql

-- 0) 기관별 게임화/시상 설정
create table if not exists public.book_program_settings (
  organization_id uuid primary key references public.organizations(id) on delete cascade,
  gamification_enabled boolean not null default true,
  leaderboard_enabled boolean not null default true,
  cheer_enabled boolean not null default true,
  streak_enabled boolean not null default true,
  rewards_enabled boolean not null default false,
  reward_mode text not null default 'manual', -- manual | auto
  monthly_reset_day smallint not null default 1,
  daily_point_cap integer not null default 120,
  late_return_penalty integer not null default -8,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint book_program_settings_reward_mode_chk check (reward_mode in ('manual', 'auto')),
  constraint book_program_settings_reset_day_chk check (monthly_reset_day between 1 and 28),
  constraint book_program_settings_daily_cap_chk check (daily_point_cap >= 0)
);

drop trigger if exists trg_book_program_settings_set_updated_at on public.book_program_settings;
create trigger trg_book_program_settings_set_updated_at
before update on public.book_program_settings
for each row execute function public.set_book_updated_at();

-- 1) 포인트 적립 규칙 (기관 커스터마이즈)
create table if not exists public.book_scoring_rules (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  rule_key text not null, -- book_complete | on_time_return | note_write | quiz_complete | streak_bonus | cheer_received | overdue_penalty
  label text not null,
  enabled boolean not null default true,
  point_value integer not null,
  unit text not null default 'per_event', -- per_event | per_day | per_book
  daily_limit integer,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint book_scoring_rules_unit_chk check (unit in ('per_event', 'per_day', 'per_book')),
  constraint book_scoring_rules_daily_limit_chk check (daily_limit is null or daily_limit >= 0),
  constraint book_scoring_rules_unique unique (organization_id, rule_key)
);

create index if not exists idx_book_scoring_rules_org
on public.book_scoring_rules(organization_id);

drop trigger if exists trg_book_scoring_rules_set_updated_at on public.book_scoring_rules;
create trigger trg_book_scoring_rules_set_updated_at
before update on public.book_scoring_rules
for each row execute function public.set_book_updated_at();

-- 2) 사용자 독서 진행도/스트릭
create table if not exists public.book_user_progress (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  profile_id uuid references public.profiles(id) on delete cascade not null,
  current_streak_days integer not null default 0,
  longest_streak_days integer not null default 0,
  last_activity_date date,
  total_books_completed integer not null default 0,
  total_notes_written integer not null default 0,
  total_quizzes_completed integer not null default 0,
  monthly_books_completed integer not null default 0,
  monthly_points integer not null default 0,
  lifetime_points integer not null default 0,
  cheers_received integer not null default 0,
  cheers_sent integer not null default 0,
  rank_tier text not null default 'seed', -- seed | bronze | silver | gold | diamond
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint book_user_progress_unique unique (organization_id, profile_id),
  constraint book_user_progress_rank_tier_chk check (rank_tier in ('seed', 'bronze', 'silver', 'gold', 'diamond'))
);

create index if not exists idx_book_user_progress_org_points
on public.book_user_progress(organization_id, monthly_points desc, lifetime_points desc);

create index if not exists idx_book_user_progress_org_streak
on public.book_user_progress(organization_id, current_streak_days desc);

drop trigger if exists trg_book_user_progress_set_updated_at on public.book_user_progress;
create trigger trg_book_user_progress_set_updated_at
before update on public.book_user_progress
for each row execute function public.set_book_updated_at();

-- 3) 응원 기능
create table if not exists public.book_cheers (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  from_profile_id uuid references public.profiles(id) on delete cascade not null,
  to_profile_id uuid references public.profiles(id) on delete cascade not null,
  target_type text not null default 'progress', -- progress | note | quiz | ranking
  target_id uuid,
  message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_date date default (timezone('utc'::text, now()))::date not null,
  constraint book_cheers_target_type_chk check (target_type in ('progress', 'note', 'quiz', 'ranking')),
  constraint book_cheers_self_chk check (from_profile_id <> to_profile_id)
);

create index if not exists idx_book_cheers_org_created_at
on public.book_cheers(organization_id, created_at desc);

create index if not exists idx_book_cheers_to_profile
on public.book_cheers(organization_id, to_profile_id, created_at desc);

create unique index if not exists idx_book_cheers_daily_unique
on public.book_cheers (
  organization_id,
  from_profile_id,
  to_profile_id,
  target_type,
  coalesce(target_id, '00000000-0000-0000-0000-000000000000'::uuid),
  created_date
);

-- 4) 리더보드 스냅샷
create table if not exists public.book_leaderboard_snapshots (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  period_type text not null, -- weekly | monthly | quarterly | yearly
  period_key text not null,  -- ex) 2026-W08, 2026-02, 2026-Q1, 2026
  profile_id uuid references public.profiles(id) on delete cascade not null,
  rank_no integer not null,
  total_points integer not null default 0,
  books_completed integer not null default 0,
  streak_days integer not null default 0,
  cheers_received integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint book_leaderboard_period_type_chk check (period_type in ('weekly', 'monthly', 'quarterly', 'yearly')),
  constraint book_leaderboard_rank_no_chk check (rank_no > 0),
  constraint book_leaderboard_unique unique (organization_id, period_type, period_key, profile_id)
);

create index if not exists idx_book_leaderboard_snapshots_period
on public.book_leaderboard_snapshots(organization_id, period_type, period_key, rank_no);

-- 5) 포인트 원장 확장
alter table public.book_point_ledger
  add column if not exists rule_key text,
  add column if not exists source_date date default (timezone('utc'::text, now()))::date,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

alter table public.book_point_ledger
  drop constraint if exists book_point_ledger_source_type_chk;

alter table public.book_point_ledger
  add constraint book_point_ledger_source_type_chk
  check (
    source_type in (
      'loan',
      'return',
      'note',
      'quiz',
      'bonus',
      'penalty',
      'completion',
      'streak',
      'cheer',
      'mission'
    )
  );

create index if not exists idx_book_point_ledger_org_source_date
on public.book_point_ledger(organization_id, profile_id, source_date desc);

-- 5-1) 기존 기관 기본값 시드
insert into public.book_program_settings (organization_id)
select o.id
from public.organizations o
on conflict (organization_id) do nothing;

insert into public.book_scoring_rules (
  organization_id,
  rule_key,
  label,
  enabled,
  point_value,
  unit
)
select
  o.id,
  rules.rule_key,
  rules.label,
  rules.enabled,
  rules.point_value,
  rules.unit
from public.organizations o
cross join (
  values
    ('book_complete', '완독/반납 완료', true, 10, 'per_book'),
    ('on_time_return', '정시 반납 보너스', true, 5, 'per_book'),
    ('note_write', '독서 메모 작성', true, 8, 'per_event'),
    ('quiz_complete', '퀴즈 완료', true, 7, 'per_event'),
    ('streak_bonus', '연속 독서 보너스', true, 10, 'per_day'),
    ('cheer_received', '응원 받음', true, 2, 'per_event'),
    ('overdue_penalty', '연체 패널티', true, -8, 'per_event')
) as rules(rule_key, label, enabled, point_value, unit)
on conflict (organization_id, rule_key) do nothing;

-- 6) RLS 활성화
alter table public.book_program_settings enable row level security;
alter table public.book_scoring_rules enable row level security;
alter table public.book_user_progress enable row level security;
alter table public.book_cheers enable row level security;
alter table public.book_leaderboard_snapshots enable row level security;

-- 7) 기존 정책 삭제
drop policy if exists "book_program_settings_select_same_org" on public.book_program_settings;
drop policy if exists "book_program_settings_insert_manager" on public.book_program_settings;
drop policy if exists "book_program_settings_update_manager" on public.book_program_settings;

drop policy if exists "book_scoring_rules_select_same_org" on public.book_scoring_rules;
drop policy if exists "book_scoring_rules_insert_manager" on public.book_scoring_rules;
drop policy if exists "book_scoring_rules_update_manager" on public.book_scoring_rules;

drop policy if exists "book_user_progress_select_same_org" on public.book_user_progress;
drop policy if exists "book_user_progress_insert_manager" on public.book_user_progress;
drop policy if exists "book_user_progress_update_manager_or_owner" on public.book_user_progress;
drop policy if exists "book_user_progress_update_manager" on public.book_user_progress;

drop policy if exists "book_cheers_select_same_org" on public.book_cheers;
drop policy if exists "book_cheers_insert_self" on public.book_cheers;
drop policy if exists "book_cheers_delete_sender_or_manager" on public.book_cheers;

drop policy if exists "book_leaderboard_snapshots_select_same_org" on public.book_leaderboard_snapshots;
drop policy if exists "book_leaderboard_snapshots_insert_manager" on public.book_leaderboard_snapshots;

-- 8) 조회 정책
create policy "book_program_settings_select_same_org"
on public.book_program_settings
for select
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_scoring_rules_select_same_org"
on public.book_scoring_rules
for select
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_user_progress_select_same_org"
on public.book_user_progress
for select
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_cheers_select_same_org"
on public.book_cheers
for select
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_leaderboard_snapshots_select_same_org"
on public.book_leaderboard_snapshots
for select
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

-- 9) 입력/수정 정책
create policy "book_program_settings_insert_manager"
on public.book_program_settings
for insert
to authenticated
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager')
  )
);

create policy "book_program_settings_update_manager"
on public.book_program_settings
for update
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager')
  )
)
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_scoring_rules_insert_manager"
on public.book_scoring_rules
for insert
to authenticated
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager')
  )
);

create policy "book_scoring_rules_update_manager"
on public.book_scoring_rules
for update
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager')
  )
)
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_user_progress_insert_manager"
on public.book_user_progress
for insert
to authenticated
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager')
  )
);

create policy "book_user_progress_update_manager"
on public.book_user_progress
for update
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager')
  )
)
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
);

create policy "book_cheers_insert_self"
on public.book_cheers
for insert
to authenticated
with check (
  from_profile_id = auth.uid()
  and organization_id = (select organization_id from public.profiles where id = auth.uid())
  and coalesce(
    (
      select s.cheer_enabled
      from public.book_program_settings s
      where s.organization_id = (select organization_id from public.profiles where id = auth.uid())
    ),
    true
  )
);

create policy "book_cheers_delete_sender_or_manager"
on public.book_cheers
for delete
to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and (
    from_profile_id = auth.uid()
    or exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role in ('admin', 'manager')
    )
  )
);

create policy "book_leaderboard_snapshots_insert_manager"
on public.book_leaderboard_snapshots
for insert
to authenticated
with check (
  organization_id = (select organization_id from public.profiles where id = auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager')
  )
);
